// GENERATED FILE — do not edit by hand.
// Regenerate with: npm run schema:manifest
//
// The migrations this deployment ships, compared against the database ledger
// by the platform schema-drift surface. scripts/platform-schema-drift.test.ts
// fails if this drifts from supabase/migrations.

import type { PlatformSchemaMigration } from "@/lib/platform-schema-drift";

export const PLATFORM_SCHEMA_MANIFEST: readonly PlatformSchemaMigration[] = [
  { version: "0001", name: "schema" },
  { version: "0002", name: "rls" },
  { version: "0003", name: "functions" },
  { version: "0004", name: "lockdown" },
  { version: "0005", name: "place_order" },
  { version: "0006", name: "sync_idempotency" },
  { version: "0007", name: "inventory_wiring" },
  { version: "0008", name: "admin_query_indexes" },
  { version: "0009", name: "admin_business_records" },
  { version: "0010", name: "inventory_catalog_fields" },
  { version: "0011", name: "employee_workspace" },
  { version: "0012", name: "employee_id_login" },
  { version: "0013", name: "current_stock_rpc" },
  { version: "0014", name: "latency_indexes" },
  { version: "0015", name: "admin_navigation_latency" },
  { version: "0016", name: "p4_branch_workflows" },
  { version: "0017", name: "product_images" },
  { version: "0018", name: "inventory_workflows" },
  { version: "0019", name: "manager_inventory_counts_read" },
  { version: "0020", name: "order_actions" },
  { version: "0021", name: "product_price_audit" },
  { version: "0022", name: "owner_signup" },
  { version: "0023", name: "store_access_and_subscriptions" },
  { version: "0024", name: "shifts_and_z_readings" },
  { version: "0025", name: "premium_billing_plan" },
  { version: "0026", name: "authenticated_append_only_hardening" },
  { version: "0027", name: "platform_operations" },
  { version: "0028", name: "support_cases" },
  { version: "0029", name: "support_cases_privileges" },
  { version: "0030", name: "suspended_account_rls" },
  { version: "0031", name: "enable_annual_billing_offers" },
  { version: "0032", name: "admin_pin_discount_policy" },
  { version: "0033", name: "human_staff_login_slugs" },
  { version: "0034", name: "pos_void_manager_approval" },
  { version: "0035", name: "fix_shift_sequence_rls" },
  { version: "0036", name: "temporary_qrph_checkout" },
  { version: "0037", name: "subscription_billing_variant" },
  { version: "0038", name: "trial_lifecycle_and_feedback" },
  { version: "0039", name: "trial_feedback_workflow" },
  { version: "0040", name: "platform_promotions" },
  { version: "0041", name: "trial_expiry_access" },
  { version: "0042", name: "display_promotions" },
  { version: "0043", name: "display_gallery" },
  { version: "0044", name: "admin_offline_mutations" },
  { version: "0045", name: "admin_sales_summary" },
  { version: "0046", name: "admin_sales_summary_weight" },
  { version: "0047", name: "inventory_tracked_products_idx" },
  { version: "0048", name: "admin_performance_samples" },
  { version: "0049", name: "default_employee_roles" },
  { version: "0050", name: "admin_performance_surfaces_and_retention" },
  { version: "0051", name: "employee_login_throttle" },
  { version: "0052", name: "platform_access_grants" },
  { version: "0053", name: "referral_program" },
  { version: "0054", name: "atomic_platform_access_grant" },
  { version: "0055", name: "online_ordering" },
  { version: "0056", name: "online_order_pos_handoff" },
  { version: "0057", name: "atomic_online_order_placement" },
  { version: "0058", name: "lockdown_online_order_handoff" },
  { version: "0059", name: "online_order_delivery" },
  { version: "0060", name: "readable_online_order_numbers" },
  { version: "0061", name: "cashier_online_order_queue" },
  { version: "0062", name: "public_menu_subdomains" },
  { version: "0063", name: "online_ordering_protection" },
  { version: "0064", name: "rpc_contract_hardening" },
  { version: "0065", name: "rpc_acl_normalization" },
  { version: "0066", name: "service_rpc_acl_fix" },
  { version: "0067", name: "verify_phone_rpc_acl_fix" },
  { version: "0068", name: "branch_billing_pricing" },
  { version: "0069", name: "active_branch_entitlement_guard" },
  { version: "0070", name: "paid_branch_entitlements" },
  { version: "0071", name: "automatic_shift_reports" },
  { version: "0072", name: "repair_paid_branch_entitlement_guard" },
  { version: "0073", name: "recipe_inventory_model" },
  { version: "0074", name: "employee_no_system_access" },
  { version: "0075", name: "extend_organization_trial" },
  { version: "0076", name: "restrict_platform_trial_rpc" },
  { version: "0077", name: "platform_operators" },
  { version: "0078", name: "adjust_platform_access_grant" },
  { version: "0079", name: "scope_admin_performance_to_organizations" },
  { version: "0080", name: "sync_health_snapshots" },
  { version: "0081", name: "sync_health_enhanced_metrics" },
  { version: "0082", name: "admin_latency_scoping" },
  { version: "0083", name: "scoped_read_rpc_acl_hardening" },
  { version: "0084", name: "schema_drift_readout" },
  { version: "0085", name: "platform_announcements" },
  { version: "0086", name: "online_ordering_business_hours" },
  { version: "0087", name: "online_ordering_status_control" },
  { version: "0088", name: "platform_support_lifecycle" },
];
