export const POS_THEME_IDS = ["modern", "classic", "soft", "dark", "bold", "system", "coastal", "sunset", "botanical", "ledger", "lechon", "restaurant", "cafe", "coffee", "latte", "bakery", "planner", "chicken", "ramen", "taqueria", "sushi", "deco"] as const;

export type PosThemeId = (typeof POS_THEME_IDS)[number];

export type PosThemeVariableName =
  | "--pos-theme-bg"
  | "--pos-theme-surface"
  | "--pos-theme-surface-panel"
  | "--pos-theme-surface-raised"
  | "--pos-theme-sidebar"
  | "--pos-theme-border"
  | "--pos-theme-border-strong"
  | "--pos-theme-text"
  | "--pos-theme-text-muted"
  | "--pos-theme-text-subtle"
  | "--pos-theme-primary-soft"
  | "--pos-theme-secondary"
  | "--pos-theme-secondary-hover"
  | "--pos-theme-highlight"
  | "--pos-theme-highlight-soft"
  | "--pos-theme-topbar"
  | "--pos-theme-topbar-text"
  | "--pos-theme-radius-card"
  | "--pos-theme-radius-btn"
  | "--pos-theme-shadow-card"
  | "--pos-theme-shadow-pop"
  | "--pos-theme-font"
  | "--pos-theme-weight"
  | "--pos-theme-letter-spacing"
  | "--pos-theme-app-pattern"
  | "--pos-theme-panel-gradient"
  | "--pos-theme-card-gradient"
  | "--pos-theme-control-gradient";

export type PosThemeVariables = Record<PosThemeVariableName, string>;

export type PosThemeDefinition = {
  id: PosThemeId;
  label: string;
  shortLabel: string;
  description: string;
  mood: string;
  variables: PosThemeVariables;
};

const shared = {
  "--pos-theme-weight": "650",
  "--pos-theme-letter-spacing": "0",
} as const;

export const POS_THEME_DEFINITIONS: Record<PosThemeId, PosThemeDefinition> = {
  modern: {
    id: "modern",
    label: "Modern Workspace",
    shortLabel: "Modern",
    description: "Layered neutrals, crisp controls, and a calm command-center feel.",
    mood: "Crisp · focused · adaptable",
    variables: {
      ...shared,
      "--pos-theme-bg": "#eef3f4",
      "--pos-theme-surface": "#ffffff",
      "--pos-theme-surface-panel": "#f5f9f9",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#e6eef0",
      "--pos-theme-border": "#d8e3e6",
      "--pos-theme-border-strong": "#b6cbd0",
      "--pos-theme-text": "#19272c",
      "--pos-theme-text-muted": "#61727a",
      "--pos-theme-text-subtle": "#91a1a7",
      "--pos-theme-primary-soft": "#e1edef",
      "--pos-theme-secondary": "#edf4f5",
      "--pos-theme-secondary-hover": "#dce9eb",
      "--pos-theme-highlight": "#1e918d",
      "--pos-theme-highlight-soft": "#d3efeb",
      "--pos-theme-topbar": "#20383c",
      "--pos-theme-topbar-text": "#f4fbfb",
      "--pos-theme-radius-card": "14px",
      "--pos-theme-radius-btn": "10px",
      "--pos-theme-shadow-card": "0 5px 18px rgba(35, 68, 76, 0.07)",
      "--pos-theme-shadow-pop": "0 18px 42px rgba(27, 52, 58, 0.16)",
      "--pos-theme-font": "Inter, ui-sans-serif, system-ui, sans-serif",
      "--pos-theme-app-pattern": "radial-gradient(circle at 8% 4%, rgba(30, 145, 141, 0.12), transparent 24%), radial-gradient(circle at 92% 82%, rgba(88, 150, 171, 0.10), transparent 26%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(238, 246, 247, 0.96))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #f7fbfb 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #edf5f6 100%)",
    },
  },
  classic: {
    id: "classic",
    label: "Classic Counter",
    shortLabel: "Classic",
    description: "Warm paper tones, ink-like rules, and a considered heritage register style.",
    mood: "Warm · crafted · familiar",
    variables: {
      ...shared,
      "--pos-theme-bg": "#eee1cf",
      "--pos-theme-surface": "#fbf5e9",
      "--pos-theme-surface-panel": "#f4e8d8",
      "--pos-theme-surface-raised": "#fffaf1",
      "--pos-theme-sidebar": "#e5d2b8",
      "--pos-theme-border": "#d5b995",
      "--pos-theme-border-strong": "#ae865d",
      "--pos-theme-text": "#402718",
      "--pos-theme-text-muted": "#826b54",
      "--pos-theme-text-subtle": "#a9947d",
      "--pos-theme-primary-soft": "#ead6bb",
      "--pos-theme-secondary": "#ecd9be",
      "--pos-theme-secondary-hover": "#ddc29f",
      "--pos-theme-highlight": "#a35e2b",
      "--pos-theme-highlight-soft": "#f0d6b6",
      "--pos-theme-topbar": "#4a2918",
      "--pos-theme-topbar-text": "#fff8eb",
      "--pos-theme-radius-card": "6px",
      "--pos-theme-radius-btn": "6px",
      "--pos-theme-shadow-card": "0 3px 0 rgba(109, 70, 35, 0.10), 0 8px 18px rgba(91, 52, 22, 0.08)",
      "--pos-theme-shadow-pop": "0 16px 34px rgba(77, 46, 22, 0.20)",
      "--pos-theme-font": "Georgia, 'Times New Roman', serif",
      "--pos-theme-weight": "600",
      "--pos-theme-letter-spacing": "0.012em",
      "--pos-theme-app-pattern": "linear-gradient(rgba(130, 81, 37, 0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(130, 81, 37, 0.035) 1px, transparent 1px)",
      "--pos-theme-panel-gradient": "linear-gradient(180deg, rgba(255, 250, 241, 0.98), rgba(242, 227, 207, 0.96))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffaf1 0%, #f4e8d8 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffaf2 0%, #ead7be 100%)",
    },
  },
  soft: {
    id: "soft",
    label: "Soft Studio",
    shortLabel: "Soft",
    description: "Lavender mist, friendly curves, and diffused surfaces for a lighter rhythm.",
    mood: "Gentle · welcoming · relaxed",
    variables: {
      ...shared,
      "--pos-theme-bg": "#efedf5",
      "--pos-theme-surface": "#fffafd",
      "--pos-theme-surface-panel": "#f8f3fa",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#ebe6f3",
      "--pos-theme-border": "#e1d9eb",
      "--pos-theme-border-strong": "#c6b6d9",
      "--pos-theme-text": "#332b42",
      "--pos-theme-text-muted": "#786b85",
      "--pos-theme-text-subtle": "#aa9fb5",
      "--pos-theme-primary-soft": "#eee5f6",
      "--pos-theme-secondary": "#f4edf8",
      "--pos-theme-secondary-hover": "#e8dcf2",
      "--pos-theme-highlight": "#b55e87",
      "--pos-theme-highlight-soft": "#f5dce8",
      "--pos-theme-topbar": "#4c3549",
      "--pos-theme-topbar-text": "#fff8fd",
      "--pos-theme-radius-card": "20px",
      "--pos-theme-radius-btn": "999px",
      "--pos-theme-shadow-card": "0 10px 26px rgba(95, 67, 116, 0.10)",
      "--pos-theme-shadow-pop": "0 20px 46px rgba(74, 49, 93, 0.17)",
      "--pos-theme-font": "'Trebuchet MS', ui-rounded, system-ui, sans-serif",
      "--pos-theme-app-pattern": "radial-gradient(circle at 15% 12%, rgba(181, 94, 135, 0.12), transparent 24%), radial-gradient(circle at 86% 14%, rgba(119, 146, 190, 0.14), transparent 23%), radial-gradient(circle at 70% 92%, rgba(220, 178, 137, 0.10), transparent 28%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 252, 255, 0.98), rgba(246, 239, 249, 0.96))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #faf2fb 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #f1e7f7 100%)",
    },
  },
  dark: {
    id: "dark",
    label: "Dark Night Shift",
    shortLabel: "Dark",
    description: "Low-glare navy layers, luminous mint signals, and crisp data rails for focused evening service.",
    mood: "Low-glare · precise · resilient",
    variables: {
      ...shared,
      "--pos-theme-bg": "#080d14",
      "--pos-theme-surface": "#0f1722",
      "--pos-theme-surface-panel": "#121d29",
      "--pos-theme-surface-raised": "#182634",
      "--pos-theme-sidebar": "#0b141e",
      "--pos-theme-border": "#253748",
      "--pos-theme-border-strong": "#3f586d",
      "--pos-theme-text": "#eef7fb",
      "--pos-theme-text-muted": "#a9bdca",
      "--pos-theme-text-subtle": "#71899a",
      "--pos-theme-primary-soft": "#123438",
      "--pos-theme-secondary": "#152430",
      "--pos-theme-secondary-hover": "#1d3342",
      "--pos-theme-highlight": "#58e2c2",
      "--pos-theme-highlight-soft": "#113c3a",
      "--pos-theme-topbar": "#070c12",
      "--pos-theme-topbar-text": "#f2fbff",
      "--pos-theme-radius-card": "10px",
      "--pos-theme-radius-btn": "8px",
      "--pos-theme-shadow-card": "0 1px 0 rgba(255, 255, 255, 0.025), 0 12px 28px rgba(0, 0, 0, 0.30)",
      "--pos-theme-shadow-pop": "0 0 0 1px rgba(88, 226, 194, 0.08), 0 28px 58px rgba(0, 0, 0, 0.52)",
      "--pos-theme-font": "var(--font-ui), 'Segoe UI', ui-sans-serif, system-ui, sans-serif",
      "--pos-theme-weight": "650",
      "--pos-theme-letter-spacing": "0.006em",
      "--pos-theme-app-pattern": "repeating-linear-gradient(0deg, transparent 0 31px, rgba(88, 226, 194, 0.025) 31px 32px), repeating-linear-gradient(90deg, transparent 0 31px, rgba(88, 226, 194, 0.02) 31px 32px), radial-gradient(circle at 84% 0%, rgba(72, 131, 181, 0.14), transparent 32%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(24, 38, 52, 0.99), rgba(10, 17, 25, 0.99))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #1a2938 0%, #111c27 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #1f3140 0%, #14222e 100%)",
    },
  },
  bold: {
    id: "bold",
    label: "Retro Comic Market",
    shortLabel: "Comic",
    description: "Newsprint cream, halftone texture, primary-color panels, and inked controls inspired by vintage comic books.",
    mood: "Retro · punchy · fast",
    variables: {
      ...shared,
      "--pos-theme-bg": "#fff3d6",
      "--pos-theme-surface": "#fffaf0",
      "--pos-theme-surface-panel": "#ffe4bf",
      "--pos-theme-surface-raised": "#fffef7",
      "--pos-theme-sidebar": "#ffd447",
      "--pos-theme-border": "#d9a83c",
      "--pos-theme-border-strong": "#17212b",
      "--pos-theme-text": "#171a1f",
      "--pos-theme-text-muted": "#5e5d57",
      "--pos-theme-text-subtle": "#8a8172",
      "--pos-theme-primary-soft": "#ffe37a",
      "--pos-theme-secondary": "#d9ecff",
      "--pos-theme-secondary-hover": "#bddcff",
      "--pos-theme-highlight": "#e54832",
      "--pos-theme-highlight-soft": "#ffd447",
      "--pos-theme-topbar": "#17212b",
      "--pos-theme-topbar-text": "#fff8e6",
      "--pos-theme-radius-card": "4px",
      "--pos-theme-radius-btn": "4px",
      "--pos-theme-shadow-card": "4px 4px 0 rgba(23, 26, 31, 0.92), 0 10px 20px rgba(185, 61, 43, 0.10)",
      "--pos-theme-shadow-pop": "7px 7px 0 rgba(23, 26, 31, 0.94), 0 22px 38px rgba(23, 26, 31, 0.18)",
      "--pos-theme-font": "'Trebuchet MS', var(--font-ui), Arial, sans-serif",
      "--pos-theme-weight": "700",
      "--pos-theme-letter-spacing": "0.004em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 1px 1px, rgba(23, 26, 31, 0.10) 0 1px, transparent 1.25px), linear-gradient(135deg, rgba(229, 72, 50, 0.055) 0 25%, transparent 25% 75%, rgba(42, 111, 187, 0.05) 75%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #fffef7 0%, #ffe0b8 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffef7 0%, #fff0d2 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #d9ecff 100%)",
    },
  },
  system: {
    id: "system",
    label: "32-Bit System",
    shortLabel: "Retro OS",
    description: "Console-grey shells, cobalt title bars, beveled controls, and memory-card color cues inspired by late-90s system menus.",
    mood: "Tactile · nostalgic · precise",
    variables: {
      ...shared,
      "--pos-theme-bg": "#aeb0ac",
      "--pos-theme-surface": "#d6d7d1",
      "--pos-theme-surface-panel": "#c4c6c1",
      "--pos-theme-surface-raised": "#e2e3dc",
      "--pos-theme-sidebar": "#b9bbb6",
      "--pos-theme-border": "#8b8e89",
      "--pos-theme-border-strong": "#4f5457",
      "--pos-theme-text": "#202326",
      "--pos-theme-text-muted": "#575c5e",
      "--pos-theme-text-subtle": "#7b807f",
      "--pos-theme-primary-soft": "#c3cfe0",
      "--pos-theme-secondary": "#c9cac4",
      "--pos-theme-secondary-hover": "#b9bab4",
      "--pos-theme-highlight": "#315d9b",
      "--pos-theme-highlight-soft": "#b5c6df",
      "--pos-theme-topbar": "#54585e",
      "--pos-theme-topbar-text": "#f3f4ef",
      "--pos-theme-radius-card": "2px",
      "--pos-theme-radius-btn": "2px",
      "--pos-theme-shadow-card": "inset 2px 2px 0 rgba(255, 255, 255, 0.72), inset -2px -2px 0 rgba(67, 70, 70, 0.28), 3px 4px 0 rgba(59, 62, 62, 0.18)",
      "--pos-theme-shadow-pop": "inset 2px 2px 0 rgba(255, 255, 255, 0.82), inset -2px -2px 0 rgba(57, 60, 61, 0.36), 6px 7px 0 rgba(51, 54, 55, 0.24)",
      "--pos-theme-font": "Tahoma, 'MS Sans Serif', 'Segoe UI', sans-serif",
      "--pos-theme-weight": "650",
      "--pos-theme-letter-spacing": "0.01em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 1px 1px, rgba(255, 255, 255, 0.15) 0 0.7px, transparent 0.85px), repeating-linear-gradient(0deg, rgba(255, 255, 255, 0.025) 0 1px, rgba(43, 46, 46, 0.025) 1px 2px)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #dedfd8 0%, #b9bbb6 100%)",
      "--pos-theme-card-gradient": "linear-gradient(135deg, #e7e8e2 0%, #c8c9c3 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #edeee8 0%, #bcbeb8 100%)",
    },
  },
  coastal: {
    id: "coastal",
    label: "Coastal Counter",
    shortLabel: "Coastal",
    description: "Sea-glass surfaces, navy anchors, and coral action cues for a bright island-service mood.",
    mood: "Fresh · breezy · confident",
    variables: {
      ...shared,
      "--pos-theme-bg": "#e9f5f5",
      "--pos-theme-surface": "#f9fffe",
      "--pos-theme-surface-panel": "#e2f1f1",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#d8ecee",
      "--pos-theme-border": "#c5dfe1",
      "--pos-theme-border-strong": "#79aeb4",
      "--pos-theme-text": "#12313a",
      "--pos-theme-text-muted": "#57777d",
      "--pos-theme-text-subtle": "#8ba8ad",
      "--pos-theme-primary-soft": "#d6eeed",
      "--pos-theme-secondary": "#eaf6f7",
      "--pos-theme-secondary-hover": "#d0e9eb",
      "--pos-theme-highlight": "#ef8068",
      "--pos-theme-highlight-soft": "#ffe1d8",
      "--pos-theme-topbar": "#103f4d",
      "--pos-theme-topbar-text": "#f5ffff",
      "--pos-theme-radius-card": "18px",
      "--pos-theme-radius-btn": "12px",
      "--pos-theme-shadow-card": "0 8px 22px rgba(31, 104, 113, 0.10)",
      "--pos-theme-shadow-pop": "0 20px 42px rgba(16, 74, 86, 0.18)",
      "--pos-theme-font": "'Trebuchet MS', ui-rounded, system-ui, sans-serif",
      "--pos-theme-app-pattern": "radial-gradient(circle at 8% 8%, rgba(239, 128, 104, 0.15), transparent 22%), radial-gradient(circle at 92% 78%, rgba(50, 153, 166, 0.13), transparent 28%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 255, 255, 0.98), rgba(224, 241, 241, 0.96))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #eef9f8 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #e3f2f3 100%)",
    },
  },
  sunset: {
    id: "sunset",
    label: "Sunset Market",
    shortLabel: "Sunset",
    description: "Terracotta warmth balanced by indigo depth, designed to make the checkout moment feel energetic.",
    mood: "Warm · expressive · social",
    variables: {
      ...shared,
      "--pos-theme-bg": "#fff0e6",
      "--pos-theme-surface": "#fffaf6",
      "--pos-theme-surface-panel": "#ffe7d8",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#f9d4bc",
      "--pos-theme-border": "#f1b697",
      "--pos-theme-border-strong": "#d87956",
      "--pos-theme-text": "#402117",
      "--pos-theme-text-muted": "#89604f",
      "--pos-theme-text-subtle": "#b18b79",
      "--pos-theme-primary-soft": "#ffe1d0",
      "--pos-theme-secondary": "#edf0ff",
      "--pos-theme-secondary-hover": "#dbe0ff",
      "--pos-theme-highlight": "#e76f51",
      "--pos-theme-highlight-soft": "#ffd0bf",
      "--pos-theme-topbar": "#342247",
      "--pos-theme-topbar-text": "#fffaff",
      "--pos-theme-radius-card": "14px",
      "--pos-theme-radius-btn": "10px",
      "--pos-theme-shadow-card": "0 8px 20px rgba(180, 83, 56, 0.12)",
      "--pos-theme-shadow-pop": "0 22px 44px rgba(77, 39, 73, 0.22)",
      "--pos-theme-font": "Arial, Helvetica, sans-serif",
      "--pos-theme-app-pattern": "none",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #fffaf6 0%, #ffe4d5 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #fff3ed 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #edf0ff 100%)",
    },
  },
  botanical: {
    id: "botanical",
    label: "Botanical Grove",
    shortLabel: "Botanical",
    description: "Sage layers, forest ink, and citrus highlights for a grounded, natural service rhythm.",
    mood: "Grounded · organic · steady",
    variables: {
      ...shared,
      "--pos-theme-bg": "#edf3e7",
      "--pos-theme-surface": "#fbfdf8",
      "--pos-theme-surface-panel": "#e5efdc",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#dce8d2",
      "--pos-theme-border": "#cbdabd",
      "--pos-theme-border-strong": "#94a986",
      "--pos-theme-text": "#20372a",
      "--pos-theme-text-muted": "#617763",
      "--pos-theme-text-subtle": "#91a191",
      "--pos-theme-primary-soft": "#dcead7",
      "--pos-theme-secondary": "#edf5e9",
      "--pos-theme-secondary-hover": "#dbead5",
      "--pos-theme-highlight": "#6b9a57",
      "--pos-theme-highlight-soft": "#d9eccd",
      "--pos-theme-topbar": "#274634",
      "--pos-theme-topbar-text": "#f7fff2",
      "--pos-theme-radius-card": "15px",
      "--pos-theme-radius-btn": "11px",
      "--pos-theme-shadow-card": "0 7px 18px rgba(49, 91, 54, 0.09)",
      "--pos-theme-shadow-pop": "0 20px 42px rgba(35, 74, 44, 0.17)",
      "--pos-theme-font": "Inter, ui-sans-serif, system-ui, sans-serif",
      "--pos-theme-app-pattern": "radial-gradient(circle at 12% 12%, rgba(107, 154, 87, 0.13), transparent 23%), radial-gradient(circle at 88% 84%, rgba(210, 157, 65, 0.11), transparent 24%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #fbfdf8 0%, #e4efd9 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #f0f7eb 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #edf5e8 100%)",
    },
  },
  ledger: {
    id: "ledger",
    label: "Monochrome Ledger",
    shortLabel: "Ledger",
    description: "Ink, paper, and a single signal-yellow action color for fast, high-clarity counter work.",
    mood: "Precise · editorial · direct",
    variables: {
      ...shared,
      "--pos-theme-bg": "#e9ecee",
      "--pos-theme-surface": "#f8f9fa",
      "--pos-theme-surface-panel": "#e1e5e7",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#dce1e4",
      "--pos-theme-border": "#c7cdd1",
      "--pos-theme-border-strong": "#8b969d",
      "--pos-theme-text": "#20262b",
      "--pos-theme-text-muted": "#616b72",
      "--pos-theme-text-subtle": "#8b959b",
      "--pos-theme-primary-soft": "#e0e5e7",
      "--pos-theme-secondary": "#eef1f2",
      "--pos-theme-secondary-hover": "#dce2e5",
      "--pos-theme-highlight": "#d59b24",
      "--pos-theme-highlight-soft": "#f8e8b8",
      "--pos-theme-topbar": "#1d2226",
      "--pos-theme-topbar-text": "#f7f8f8",
      "--pos-theme-radius-card": "4px",
      "--pos-theme-radius-btn": "4px",
      "--pos-theme-shadow-card": "0 2px 0 rgba(32, 38, 43, 0.08)",
      "--pos-theme-shadow-pop": "0 12px 28px rgba(32, 38, 43, 0.18)",
      "--pos-theme-font": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      "--pos-theme-weight": "650",
      "--pos-theme-letter-spacing": "0.015em",
      "--pos-theme-app-pattern": "none",
      "--pos-theme-panel-gradient": "linear-gradient(180deg, #ffffff 0%, #e6e9eb 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #f0f2f3 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #e7ebed 100%)",
    },
  },
  lechon: {
    id: "lechon",
    label: "Lechon House Ember",
    shortLabel: "Lechon House",
    description: "Roasted copper, charcoal accents, and woven-table texture for proud Filipino feast service.",
    mood: "Smoky · festive · proudly local",
    variables: {
      ...shared,
      "--pos-theme-bg": "#f2e7d8",
      "--pos-theme-surface": "#fffaf2",
      "--pos-theme-surface-panel": "#f1dfca",
      "--pos-theme-surface-raised": "#fffdf8",
      "--pos-theme-sidebar": "#ead2b8",
      "--pos-theme-border": "#ddc1a2",
      "--pos-theme-border-strong": "#a96b43",
      "--pos-theme-text": "#2f1c16",
      "--pos-theme-text-muted": "#775d4e",
      "--pos-theme-text-subtle": "#a28b7c",
      "--pos-theme-primary-soft": "#f0d2b3",
      "--pos-theme-secondary": "#f5e5d2",
      "--pos-theme-secondary-hover": "#ead0b4",
      "--pos-theme-highlight": "#c65a2b",
      "--pos-theme-highlight-soft": "#f3c39f",
      "--pos-theme-topbar": "#341a14",
      "--pos-theme-topbar-text": "#fff8ed",
      "--pos-theme-radius-card": "12px",
      "--pos-theme-radius-btn": "9px",
      "--pos-theme-shadow-card": "0 7px 18px rgba(86, 43, 22, 0.11)",
      "--pos-theme-shadow-pop": "0 22px 46px rgba(56, 27, 18, 0.22)",
      "--pos-theme-font": "'Trebuchet MS', Arial, system-ui, sans-serif",
      "--pos-theme-weight": "680",
      "--pos-theme-letter-spacing": "0.006em",
      "--pos-theme-app-pattern": "repeating-linear-gradient(116deg, rgba(86, 48, 26, 0.032) 0 1px, transparent 1px 10px), radial-gradient(circle at 12% 8%, rgba(198, 90, 43, 0.14), transparent 24%)",
      "--pos-theme-panel-gradient": "linear-gradient(150deg, rgba(255, 250, 242, 0.98), rgba(237, 214, 187, 0.97))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffdf8 0%, #f7eadb 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffdf9 0%, #f1deca 100%)",
    },
  },
  restaurant: {
    id: "restaurant",
    label: "Restaurant Maison",
    shortLabel: "Restaurant",
    description: "Linen neutrals, merlot details, and editorial typography for polished table-service dining.",
    mood: "Refined · composed · hospitable",
    variables: {
      ...shared,
      "--pos-theme-bg": "#eeebe5",
      "--pos-theme-surface": "#fffdf9",
      "--pos-theme-surface-panel": "#f2ede6",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#e6dfd6",
      "--pos-theme-border": "#d8cfc5",
      "--pos-theme-border-strong": "#988a7e",
      "--pos-theme-text": "#27211f",
      "--pos-theme-text-muted": "#746963",
      "--pos-theme-text-subtle": "#9e928a",
      "--pos-theme-primary-soft": "#eee1e3",
      "--pos-theme-secondary": "#f0ece7",
      "--pos-theme-secondary-hover": "#e1d9d1",
      "--pos-theme-highlight": "#7d3042",
      "--pos-theme-highlight-soft": "#ead2d7",
      "--pos-theme-topbar": "#26211f",
      "--pos-theme-topbar-text": "#fffaf3",
      "--pos-theme-radius-card": "8px",
      "--pos-theme-radius-btn": "7px",
      "--pos-theme-shadow-card": "0 6px 16px rgba(48, 38, 33, 0.075)",
      "--pos-theme-shadow-pop": "0 22px 48px rgba(45, 32, 29, 0.18)",
      "--pos-theme-font": "'Palatino Linotype', Palatino, Georgia, serif",
      "--pos-theme-weight": "600",
      "--pos-theme-letter-spacing": "0.008em",
      "--pos-theme-app-pattern": "repeating-linear-gradient(0deg, rgba(74, 58, 48, 0.025) 0 1px, transparent 1px 7px), repeating-linear-gradient(90deg, rgba(74, 58, 48, 0.018) 0 1px, transparent 1px 9px)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 253, 249, 0.99), rgba(238, 232, 224, 0.97))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #f6f1eb 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #eee9e3 100%)",
    },
  },
  cafe: {
    id: "cafe",
    label: "Café Daylight",
    shortLabel: "Café",
    description: "Sunlit cream, fresh sage, and terracotta cues for an airy all-day café counter.",
    mood: "Bright · social · easygoing",
    variables: {
      ...shared,
      "--pos-theme-bg": "#f5efe3",
      "--pos-theme-surface": "#fffdf7",
      "--pos-theme-surface-panel": "#eef1e5",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#dfe8d7",
      "--pos-theme-border": "#d9d8c8",
      "--pos-theme-border-strong": "#9eaa8f",
      "--pos-theme-text": "#26332c",
      "--pos-theme-text-muted": "#68756d",
      "--pos-theme-text-subtle": "#96a098",
      "--pos-theme-primary-soft": "#e2ead9",
      "--pos-theme-secondary": "#f1eee4",
      "--pos-theme-secondary-hover": "#e5e0d2",
      "--pos-theme-highlight": "#cb6e4d",
      "--pos-theme-highlight-soft": "#f5d7c8",
      "--pos-theme-topbar": "#355447",
      "--pos-theme-topbar-text": "#fffdf5",
      "--pos-theme-radius-card": "18px",
      "--pos-theme-radius-btn": "14px",
      "--pos-theme-shadow-card": "0 8px 22px rgba(74, 91, 73, 0.09)",
      "--pos-theme-shadow-pop": "0 22px 46px rgba(53, 74, 60, 0.17)",
      "--pos-theme-font": "'Avenir Next', 'Trebuchet MS', system-ui, sans-serif",
      "--pos-theme-weight": "650",
      "--pos-theme-letter-spacing": "0.004em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 10% 8%, rgba(203, 110, 77, 0.12), transparent 24%), radial-gradient(circle at 88% 80%, rgba(108, 137, 91, 0.13), transparent 27%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 253, 247, 0.99), rgba(232, 237, 220, 0.97))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #f8f5ec 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #eef1e6 100%)",
    },
  },
  coffee: {
    id: "coffee",
    label: "Coffee Roastery",
    shortLabel: "Coffee Shop",
    description: "Espresso layers, caramel highlights, and a moody roastery texture for specialty coffee service.",
    mood: "Crafted · focused · aromatic",
    variables: {
      ...shared,
      "--pos-theme-bg": "#17120f",
      "--pos-theme-surface": "#211a16",
      "--pos-theme-surface-panel": "#2a211c",
      "--pos-theme-surface-raised": "#302620",
      "--pos-theme-sidebar": "#1d1714",
      "--pos-theme-border": "#493a31",
      "--pos-theme-border-strong": "#735b49",
      "--pos-theme-text": "#f4eadf",
      "--pos-theme-text-muted": "#c1ac9c",
      "--pos-theme-text-subtle": "#8f7868",
      "--pos-theme-primary-soft": "#3a2b23",
      "--pos-theme-secondary": "#332821",
      "--pos-theme-secondary-hover": "#44352b",
      "--pos-theme-highlight": "#c89258",
      "--pos-theme-highlight-soft": "#5a3e29",
      "--pos-theme-topbar": "#100c0a",
      "--pos-theme-topbar-text": "#fff3e5",
      "--pos-theme-radius-card": "13px",
      "--pos-theme-radius-btn": "10px",
      "--pos-theme-shadow-card": "0 10px 24px rgba(0, 0, 0, 0.28)",
      "--pos-theme-shadow-pop": "0 26px 54px rgba(0, 0, 0, 0.46)",
      "--pos-theme-font": "'Trebuchet MS', Arial, system-ui, sans-serif",
      "--pos-theme-weight": "650",
      "--pos-theme-letter-spacing": "0.006em",
      "--pos-theme-app-pattern": "radial-gradient(ellipse at 18% 14%, rgba(200, 146, 88, 0.07) 0 2px, transparent 2.5px), radial-gradient(ellipse at 72% 68%, rgba(200, 146, 88, 0.055) 0 2px, transparent 2.5px)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(48, 38, 32, 0.99), rgba(29, 22, 18, 0.99))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #302620 0%, #251d19 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #3a2e27 0%, #29201b 100%)",
    },
  },
  latte: {
    id: "latte",
    label: "Latte Minimal",
    shortLabel: "Warm Coffee",
    description: "Milk-foam neutrals, espresso ink, and a quiet caramel accent for modern specialty coffee counters.",
    mood: "Warm · minimal · refined",
    variables: {
      ...shared,
      "--pos-theme-bg": "#f2ebe3",
      "--pos-theme-surface": "#fffaf4",
      "--pos-theme-surface-panel": "#f4ebe2",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#ede2d7",
      "--pos-theme-border": "#e2d5c8",
      "--pos-theme-border-strong": "#c2ae9c",
      "--pos-theme-text": "#302722",
      "--pos-theme-text-muted": "#7a6a60",
      "--pos-theme-text-subtle": "#aa998d",
      "--pos-theme-primary-soft": "#f4e3d4",
      "--pos-theme-secondary": "#f2e8de",
      "--pos-theme-secondary-hover": "#e8d9cb",
      "--pos-theme-highlight": "#b96d3d",
      "--pos-theme-highlight-soft": "#f2d8c5",
      "--pos-theme-topbar": "#3b2d27",
      "--pos-theme-topbar-text": "#fff9f3",
      "--pos-theme-radius-card": "14px",
      "--pos-theme-radius-btn": "10px",
      "--pos-theme-shadow-card": "0 7px 20px rgba(78, 53, 38, 0.08)",
      "--pos-theme-shadow-pop": "0 18px 38px rgba(72, 47, 32, 0.15)",
      "--pos-theme-font": "'Avenir Next', 'Segoe UI', var(--font-ui), sans-serif",
      "--pos-theme-weight": "620",
      "--pos-theme-letter-spacing": "0.003em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 8% 0%, rgba(185, 109, 61, 0.10), transparent 28%), radial-gradient(circle at 94% 88%, rgba(103, 73, 57, 0.055), transparent 25%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 253, 249, 0.99), rgba(241, 229, 218, 0.97))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #fbf5ef 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #f3e9df 100%)",
    },
  },
  bakery: {
    id: "bakery",
    label: "Bakery Pâtisserie",
    shortLabel: "Bakery",
    description: "Buttercream surfaces, berry ink, and delicate pastry-shop details for a joyful display counter.",
    mood: "Delicate · joyful · handcrafted",
    variables: {
      ...shared,
      "--pos-theme-bg": "#faeee9",
      "--pos-theme-surface": "#fffaf7",
      "--pos-theme-surface-panel": "#f8e3df",
      "--pos-theme-surface-raised": "#ffffff",
      "--pos-theme-sidebar": "#f1d8d4",
      "--pos-theme-border": "#e8c9c2",
      "--pos-theme-border-strong": "#bf8e86",
      "--pos-theme-text": "#41292f",
      "--pos-theme-text-muted": "#86696d",
      "--pos-theme-text-subtle": "#af9395",
      "--pos-theme-primary-soft": "#f6d9dd",
      "--pos-theme-secondary": "#fff0df",
      "--pos-theme-secondary-hover": "#f4dfca",
      "--pos-theme-highlight": "#a9435d",
      "--pos-theme-highlight-soft": "#f4cbd5",
      "--pos-theme-topbar": "#6d3144",
      "--pos-theme-topbar-text": "#fff8f4",
      "--pos-theme-radius-card": "18px",
      "--pos-theme-radius-btn": "12px",
      "--pos-theme-shadow-card": "0 9px 22px rgba(113, 61, 72, 0.10)",
      "--pos-theme-shadow-pop": "0 22px 48px rgba(95, 47, 62, 0.20)",
      "--pos-theme-font": "Georgia, 'Times New Roman', serif",
      "--pos-theme-weight": "600",
      "--pos-theme-letter-spacing": "0.006em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 12px 12px, rgba(169, 67, 93, 0.035) 0 2px, transparent 2.5px), radial-gradient(circle at 36px 36px, rgba(213, 159, 88, 0.04) 0 2px, transparent 2.5px)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(255, 250, 247, 0.99), rgba(246, 222, 218, 0.98))",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #ffffff 0%, #fff1ed 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #ffffff 0%, #fff0df 100%)",
    },
  },
  planner: {
    id: "planner",
    label: "Evergreen Planner",
    shortLabel: "Planner",
    description: "Notebook lines, tabbed navigation, and deep evergreen details for a calm, modern café counter.",
    mood: "Minimal · tactile · organized",
    variables: {
      ...shared,
      "--pos-theme-bg": "#e9ece4",
      "--pos-theme-surface": "#fbfaf4",
      "--pos-theme-surface-panel": "#f1f1e8",
      "--pos-theme-surface-raised": "#fffef9",
      "--pos-theme-sidebar": "#dfe6dd",
      "--pos-theme-border": "#cbd2c6",
      "--pos-theme-border-strong": "#8fa092",
      "--pos-theme-text": "#19342d",
      "--pos-theme-text-muted": "#586b64",
      "--pos-theme-text-subtle": "#7b8983",
      "--pos-theme-primary-soft": "#dce8df",
      "--pos-theme-secondary": "#edf1ea",
      "--pos-theme-secondary-hover": "#dfe7de",
      "--pos-theme-highlight": "#b88746",
      "--pos-theme-highlight-soft": "#eadcc5",
      "--pos-theme-topbar": "#15372f",
      "--pos-theme-topbar-text": "#fffdf5",
      "--pos-theme-radius-card": "14px",
      "--pos-theme-radius-btn": "999px",
      "--pos-theme-shadow-card": "0 1px 2px rgba(28, 52, 44, 0.06), 0 8px 22px rgba(28, 52, 44, 0.07)",
      "--pos-theme-shadow-pop": "0 20px 44px rgba(25, 52, 45, 0.16)",
      "--pos-theme-font": "'Avenir Next', 'Segoe UI', var(--font-ui), sans-serif",
      "--pos-theme-weight": "620",
      "--pos-theme-letter-spacing": "0.002em",
      "--pos-theme-app-pattern": "linear-gradient(rgba(21, 55, 47, 0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(21, 55, 47, 0.018) 1px, transparent 1px)",
      "--pos-theme-panel-gradient": "repeating-linear-gradient(0deg, rgba(21, 55, 47, 0.035) 0 1px, transparent 1px 29px), linear-gradient(145deg, #fffef9 0%, #eef1e8 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffef9 0%, #f5f5ee 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffef9 0%, #edf1ea 100%)",
    },
  },
  chicken: {
    id: "chicken",
    label: "Golden Crunch Chicken",
    shortLabel: "Crispy Chicken",
    description: "Ketchup red, golden fry-box yellow, checkerboard details, and bold quick-service controls.",
    mood: "Crispy · playful · high-energy",
    variables: {
      ...shared,
      "--pos-theme-bg": "#ffe8b4",
      "--pos-theme-surface": "#fff8e6",
      "--pos-theme-surface-panel": "#ffd66f",
      "--pos-theme-surface-raised": "#fffdf5",
      "--pos-theme-sidebar": "#f5ba25",
      "--pos-theme-border": "#d59a22",
      "--pos-theme-border-strong": "#2d2118",
      "--pos-theme-text": "#251b14",
      "--pos-theme-text-muted": "#6b5140",
      "--pos-theme-text-subtle": "#92745b",
      "--pos-theme-primary-soft": "#ffe08a",
      "--pos-theme-secondary": "#fff1cf",
      "--pos-theme-secondary-hover": "#ffdf91",
      "--pos-theme-highlight": "#d9432f",
      "--pos-theme-highlight-soft": "#ffc934",
      "--pos-theme-topbar": "#b92723",
      "--pos-theme-topbar-text": "#fff8df",
      "--pos-theme-radius-card": "7px",
      "--pos-theme-radius-btn": "6px",
      "--pos-theme-shadow-card": "4px 5px 0 rgba(45, 33, 24, 0.90), 0 12px 22px rgba(156, 52, 30, 0.12)",
      "--pos-theme-shadow-pop": "7px 8px 0 rgba(45, 33, 24, 0.94), 0 22px 38px rgba(102, 37, 24, 0.20)",
      "--pos-theme-font": "'Trebuchet MS', Arial, var(--font-ui), sans-serif",
      "--pos-theme-weight": "760",
      "--pos-theme-letter-spacing": "0.006em",
      "--pos-theme-app-pattern": "linear-gradient(45deg, rgba(185, 39, 35, 0.045) 25%, transparent 25% 75%, rgba(185, 39, 35, 0.045) 75%), linear-gradient(45deg, rgba(185, 39, 35, 0.045) 25%, transparent 25% 75%, rgba(185, 39, 35, 0.045) 75%)",
      "--pos-theme-panel-gradient": "linear-gradient(150deg, #fffdf5 0%, #ffe09a 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffdf5 0%, #fff0c9 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffef8 0%, #ffe5a5 100%)",
    },
  },
  ramen: {
    id: "ramen",
    label: "Neon Noodle Alley",
    shortLabel: "Ramen Alley",
    description: "Midnight indigo, neon signage, and glowing ticket rails for high-tempo ramen and night-market service.",
    mood: "Electric · nocturnal · kinetic",
    variables: {
      ...shared,
      "--pos-theme-bg": "#080c20",
      "--pos-theme-surface": "#10162d",
      "--pos-theme-surface-panel": "#151c36",
      "--pos-theme-surface-raised": "#1b2443",
      "--pos-theme-sidebar": "#0b1129",
      "--pos-theme-border": "#2b3563",
      "--pos-theme-border-strong": "#5965a0",
      "--pos-theme-text": "#f7f2ea",
      "--pos-theme-text-muted": "#b5b3ca",
      "--pos-theme-text-subtle": "#8583a4",
      "--pos-theme-primary-soft": "#173044",
      "--pos-theme-secondary": "#141d3b",
      "--pos-theme-secondary-hover": "#222d55",
      "--pos-theme-highlight": "#ff4f7d",
      "--pos-theme-highlight-soft": "#47213c",
      "--pos-theme-topbar": "#070918",
      "--pos-theme-topbar-text": "#fff7ee",
      "--pos-theme-radius-card": "10px",
      "--pos-theme-radius-btn": "8px",
      "--pos-theme-shadow-card": "0 0 0 1px rgba(45, 227, 219, 0.08), 0 14px 30px rgba(0, 0, 0, 0.38)",
      "--pos-theme-shadow-pop": "0 0 0 1px rgba(255, 79, 125, 0.38), 0 0 26px rgba(255, 79, 125, 0.16), 0 24px 52px rgba(0, 0, 0, 0.52)",
      "--pos-theme-font": "'Arial Narrow', 'Segoe UI', var(--font-ui), sans-serif",
      "--pos-theme-weight": "680",
      "--pos-theme-letter-spacing": "0.018em",
      "--pos-theme-app-pattern": "repeating-linear-gradient(90deg, transparent 0 47px, rgba(45, 227, 219, 0.025) 47px 48px), repeating-linear-gradient(0deg, transparent 0 47px, rgba(255, 79, 125, 0.022) 47px 48px), radial-gradient(circle at 82% 4%, rgba(255, 79, 125, 0.16), transparent 25%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, rgba(27, 36, 67, 0.99), rgba(10, 15, 37, 0.99))",
      "--pos-theme-card-gradient": "linear-gradient(155deg, #1a2344 0%, #0f1630 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #202b50 0%, #121a37 100%)",
    },
  },
  taqueria: {
    id: "taqueria",
    label: "Papel Picado Taqueria",
    shortLabel: "Taqueria",
    description: "Cut-paper color, corn-tortilla warmth, and hand-painted menu shapes for lively street-food counters.",
    mood: "Festive · handmade · generous",
    variables: {
      ...shared,
      "--pos-theme-bg": "#f7e0b0",
      "--pos-theme-surface": "#fff8e7",
      "--pos-theme-surface-panel": "#f4cb76",
      "--pos-theme-surface-raised": "#fffdf3",
      "--pos-theme-sidebar": "#0b7b76",
      "--pos-theme-border": "#c87d43",
      "--pos-theme-border-strong": "#3d281f",
      "--pos-theme-text": "#2e1d16",
      "--pos-theme-text-muted": "#705242",
      "--pos-theme-text-subtle": "#95745c",
      "--pos-theme-primary-soft": "#d0e7dd",
      "--pos-theme-secondary": "#fff0c8",
      "--pos-theme-secondary-hover": "#f5d98f",
      "--pos-theme-highlight": "#e24a2f",
      "--pos-theme-highlight-soft": "#ffcf4e",
      "--pos-theme-topbar": "#075f5c",
      "--pos-theme-topbar-text": "#fff8e9",
      "--pos-theme-radius-card": "12px",
      "--pos-theme-radius-btn": "9px",
      "--pos-theme-shadow-card": "4px 5px 0 rgba(61, 40, 31, 0.80), 0 10px 20px rgba(113, 62, 35, 0.10)",
      "--pos-theme-shadow-pop": "7px 8px 0 rgba(61, 40, 31, 0.88), 0 22px 38px rgba(88, 45, 30, 0.18)",
      "--pos-theme-font": "'Trebuchet MS', 'Arial Rounded MT Bold', Arial, sans-serif",
      "--pos-theme-weight": "720",
      "--pos-theme-letter-spacing": "0.008em",
      "--pos-theme-app-pattern": "radial-gradient(circle at 10px 10px, rgba(11, 123, 118, 0.05) 0 3px, transparent 3.5px), radial-gradient(circle at 30px 30px, rgba(226, 74, 47, 0.045) 0 3px, transparent 3.5px)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #fffdf3 0%, #f6d890 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffdf3 0%, #ffedc2 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffef7 0%, #f7dda2 100%)",
    },
  },
  sushi: {
    id: "sushi",
    label: "Ink & Nori Sushi",
    shortLabel: "Sushi Bar",
    description: "Washi paper, indigo ink, and vermilion stamp details for a quiet, precise sushi counter.",
    mood: "Precise · serene · crafted",
    variables: {
      ...shared,
      "--pos-theme-bg": "#e9e4da",
      "--pos-theme-surface": "#faf8f1",
      "--pos-theme-surface-panel": "#eeebe2",
      "--pos-theme-surface-raised": "#fffdfa",
      "--pos-theme-sidebar": "#deded7",
      "--pos-theme-border": "#c9c1b4",
      "--pos-theme-border-strong": "#626569",
      "--pos-theme-text": "#1d2529",
      "--pos-theme-text-muted": "#60696c",
      "--pos-theme-text-subtle": "#858d8d",
      "--pos-theme-primary-soft": "#dfe6e4",
      "--pos-theme-secondary": "#eeede8",
      "--pos-theme-secondary-hover": "#deded8",
      "--pos-theme-highlight": "#c94735",
      "--pos-theme-highlight-soft": "#eed5cf",
      "--pos-theme-topbar": "#152d36",
      "--pos-theme-topbar-text": "#fffdf7",
      "--pos-theme-radius-card": "4px",
      "--pos-theme-radius-btn": "4px",
      "--pos-theme-shadow-card": "0 2px 0 rgba(29, 37, 41, 0.08), 0 9px 22px rgba(29, 37, 41, 0.07)",
      "--pos-theme-shadow-pop": "0 18px 38px rgba(24, 36, 42, 0.17)",
      "--pos-theme-font": "'Yu Gothic UI', 'Hiragino Sans', 'Segoe UI', var(--font-ui), sans-serif",
      "--pos-theme-weight": "620",
      "--pos-theme-letter-spacing": "0.012em",
      "--pos-theme-app-pattern": "repeating-linear-gradient(112deg, rgba(21, 45, 54, 0.022) 0 1px, transparent 1px 8px), radial-gradient(circle at 88% 12%, rgba(201, 71, 53, 0.08), transparent 20%)",
      "--pos-theme-panel-gradient": "repeating-linear-gradient(0deg, rgba(21, 45, 54, 0.028) 0 1px, transparent 1px 31px), linear-gradient(145deg, #fffdfa 0%, #ebe9e1 100%)",
      "--pos-theme-card-gradient": "linear-gradient(180deg, #fffdfa 0%, #f2f0e9 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #fffdfa 0%, #e9e8e2 100%)",
    },
  },
  deco: {
    id: "deco",
    label: "Deco Supper Club",
    shortLabel: "Supper Club",
    description: "Black lacquer, champagne gold, and geometric framing for an elegant late-night dining room.",
    mood: "Glamorous · cinematic · composed",
    variables: {
      ...shared,
      "--pos-theme-bg": "#0d1110",
      "--pos-theme-surface": "#151b19",
      "--pos-theme-surface-panel": "#1a2220",
      "--pos-theme-surface-raised": "#202a27",
      "--pos-theme-sidebar": "#111816",
      "--pos-theme-border": "#354640",
      "--pos-theme-border-strong": "#796b4d",
      "--pos-theme-text": "#f5eedf",
      "--pos-theme-text-muted": "#c0b7a7",
      "--pos-theme-text-subtle": "#8f8a7f",
      "--pos-theme-primary-soft": "#28342f",
      "--pos-theme-secondary": "#202925",
      "--pos-theme-secondary-hover": "#2c3732",
      "--pos-theme-highlight": "#d2aa5c",
      "--pos-theme-highlight-soft": "#4c4029",
      "--pos-theme-topbar": "#070b0a",
      "--pos-theme-topbar-text": "#fff6de",
      "--pos-theme-radius-card": "2px",
      "--pos-theme-radius-btn": "2px",
      "--pos-theme-shadow-card": "0 0 0 1px rgba(210, 170, 92, 0.10), 0 14px 30px rgba(0, 0, 0, 0.32)",
      "--pos-theme-shadow-pop": "0 0 0 1px rgba(210, 170, 92, 0.34), 0 28px 56px rgba(0, 0, 0, 0.52)",
      "--pos-theme-font": "Copperplate, 'Century Gothic', Georgia, serif",
      "--pos-theme-weight": "620",
      "--pos-theme-letter-spacing": "0.025em",
      "--pos-theme-app-pattern": "linear-gradient(30deg, rgba(210, 170, 92, 0.028) 12%, transparent 12.5% 87%, rgba(210, 170, 92, 0.028) 87.5%), linear-gradient(150deg, rgba(210, 170, 92, 0.022) 12%, transparent 12.5% 87%, rgba(210, 170, 92, 0.022) 87.5%)",
      "--pos-theme-panel-gradient": "linear-gradient(145deg, #202a27 0%, #101614 100%)",
      "--pos-theme-card-gradient": "linear-gradient(155deg, #202925 0%, #121816 100%)",
      "--pos-theme-control-gradient": "linear-gradient(180deg, #29332f 0%, #18201d 100%)",
    },
  },
};

export const POS_THEME_OPTIONS = POS_THEME_IDS.map((id) => POS_THEME_DEFINITIONS[id]);

export function isPosThemeId(value: unknown): value is PosThemeId {
  return typeof value === "string" && POS_THEME_IDS.includes(value as PosThemeId);
}

export function getPosTheme(value: string | null | undefined): PosThemeDefinition {
  if (isPosThemeId(value)) {
    return POS_THEME_DEFINITIONS[value as PosThemeId];
  }
  return POS_THEME_DEFINITIONS.modern;
}

type PosThemeDisplayColors = {
  heading: string;
  accentInk: string;
};

const MINIMUM_TEXT_CONTRAST = 4.5;

function hexLuminance(value: string) {
  const match = /^#([\da-f]{6})$/i.exec(value);
  if (!match) return null;
  const channels = match[1].match(/[\da-f]{2}/gi)?.map((channel) => Number.parseInt(channel, 16) / 255);
  if (!channels || channels.length !== 3) return null;
  const [red, green, blue] = channels.map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
  return (0.2126 * red) + (0.7152 * green) + (0.0722 * blue);
}

function contrastRatio(foreground: string, background: string) {
  const foregroundLuminance = hexLuminance(foreground);
  const backgroundLuminance = hexLuminance(background);
  if (foregroundLuminance === null || backgroundLuminance === null) return 0;
  const lighter = Math.max(foregroundLuminance, backgroundLuminance);
  const darker = Math.min(foregroundLuminance, backgroundLuminance);
  return (lighter + 0.05) / (darker + 0.05);
}

function pickReadableColor(background: string, candidates: string[]) {
  const scoredCandidates = candidates.map((candidate) => ({
    candidate,
    contrast: contrastRatio(candidate, background),
  }));
  return scoredCandidates.find(({ contrast }) => contrast >= MINIMUM_TEXT_CONTRAST)?.candidate
    ?? scoredCandidates.reduce((best, current) => current.contrast > best.contrast ? current : best).candidate;
}

export function getPosThemeDisplayColors(value: string | null | undefined): PosThemeDisplayColors {
  const theme = getPosTheme(value).variables;
  const background = theme["--pos-theme-bg"];
  const text = theme["--pos-theme-text"];
  const brandHeading = theme["--pos-theme-topbar"];
  const accent = theme["--pos-theme-highlight"];
  const topbarText = theme["--pos-theme-topbar-text"];

  return {
    heading: pickReadableColor(background, [brandHeading, text]),
    accentInk: pickReadableColor(accent, [text, topbarText, "#000000", "#ffffff"]),
  };
}
