"use client";

import { useActionState } from "react";
import { AdminIcon } from "@/components/admin/AdminIcon";
import type { PlatformTrialCoupon } from "@/lib/platform-trial-coupons-server";
import { createPlatformTrialCoupon, togglePlatformTrialCoupon, type PlatformActionState } from "./actions";

const INITIAL_STATE: PlatformActionState = { ok: false, message: "" };
const FIELD_CLASS = "mt-1 w-full rounded-xl border border-line-strong bg-raised px-3 py-2.5 text-sm font-semibold text-ink outline-none focus:border-primary focus:ring-2 focus:ring-primary/10";

export function PlatformTrialCouponEditor({ schemaAvailable, coupons, canManage }: { schemaAvailable: boolean; coupons: PlatformTrialCoupon[]; canManage: boolean }) {
  const [state, formAction, pending] = useActionState(createPlatformTrialCoupon, INITIAL_STATE);
  return <section className="mt-6 overflow-hidden rounded-[20px] border border-line bg-surface shadow-[var(--shadow-card)]" aria-labelledby="trial-coupons-heading">
    <div className="border-b border-line px-5 py-5 sm:px-6"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-accent">Acquisition offer</p><h2 id="trial-coupons-heading" className="mt-1 text-xl font-extrabold">Free trial coupons</h2><p className="mt-1 max-w-2xl text-sm leading-5 text-ink-muted">Create a code that a business owner can redeem once while their account is in an active trial. It adds calendar months to the current trial end.</p></div>
    <div className="grid gap-6 p-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] sm:p-6">
      <form action={formAction} className="space-y-3">
        <div className="grid gap-3 sm:grid-cols-2"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-code">Code<input id="trial-coupon-code" name="code" required maxLength={32} placeholder="WELCOME3M" className={`${FIELD_CLASS} uppercase`} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-name">Internal name<input id="trial-coupon-name" name="name" required maxLength={80} placeholder="Three month launch offer" className={FIELD_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label></div>
        <div className="grid gap-3 sm:grid-cols-3"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-months">Free months<input id="trial-coupon-months" name="months" type="number" min="1" max="12" step="1" defaultValue="1" required className={FIELD_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-starts">Starts<input id="trial-coupon-starts" name="starts_at" type="datetime-local" className={FIELD_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-ends">Ends<input id="trial-coupon-ends" name="ends_at" type="datetime-local" className={FIELD_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label></div>
        <label className="block max-w-xs text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="trial-coupon-limit">Total claims<input id="trial-coupon-limit" name="max_redemptions" type="number" min="1" max="1000000" step="1" placeholder="Unlimited" className={FIELD_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label>
        {state.message && <p role={state.ok ? "status" : "alert"} className={`rounded-xl border px-3 py-2.5 text-sm font-semibold ${state.ok ? "border-success/25 bg-success/10 text-success" : "border-danger/25 bg-danger-soft text-danger"}`}>{state.message}</p>}
        {!schemaAvailable && <p role="status" className="rounded-xl border border-warning/35 bg-warning/10 px-3 py-2.5 text-xs font-semibold leading-5 text-ink">Apply <code className="font-extrabold">0094_platform_trial_coupons.sql</code> to enable trial coupons.</p>}
        <button type="submit" disabled={!canManage || !schemaAvailable || pending} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-extrabold uppercase tracking-wide text-primary-fg disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Creating…" : "Create trial coupon"}<AdminIcon name="plus" size={14} /></button>
        {!canManage && <p role="status" className="text-xs font-semibold text-ink-muted">Coupon management is limited to Billing and Owner operators.</p>}
      </form>
      <div className="overflow-x-auto rounded-xl border border-line"><table className="min-w-[560px] w-full text-left text-sm"><thead className="bg-raised text-[10px] uppercase tracking-wide text-ink-muted"><tr><th className="px-4 py-3">Coupon</th><th className="px-3 py-3">Offer</th><th className="px-3 py-3">Claims</th><th className="px-4 py-3 text-right">Status</th></tr></thead><tbody className="divide-y divide-line">{coupons.length ? coupons.map((coupon) => <CouponRow key={coupon.id} coupon={coupon} canManage={canManage} schemaAvailable={schemaAvailable} />) : <tr><td colSpan={4} className="px-4 py-8 text-center text-xs font-semibold text-ink-muted">No free trial coupons yet.</td></tr>}</tbody></table></div>
    </div>
  </section>;
}

function CouponRow({ coupon, canManage, schemaAvailable }: { coupon: PlatformTrialCoupon; canManage: boolean; schemaAvailable: boolean }) {
  const [state, action, pending] = useActionState(togglePlatformTrialCoupon, INITIAL_STATE);
  const end = coupon.endsAt ? new Date(coupon.endsAt).toLocaleDateString("en-SG", { timeZone: "Asia/Singapore" }) : null;
  return <tr><td className="px-4 py-3"><strong className="block font-extrabold text-primary">{coupon.code}</strong><span className="text-xs text-ink-muted">{coupon.name}{end ? ` · until ${end}` : ""}</span>{state.message && <span role={state.ok ? "status" : "alert"} className="block text-[10px] text-ink-muted">{state.message}</span>}</td><td className="px-3 py-3 text-xs font-bold">{coupon.months} month{coupon.months === 1 ? "" : "s"}</td><td className="px-3 py-3 text-xs tabular-nums">{coupon.redemptions}{coupon.maxRedemptions ? `/${coupon.maxRedemptions}` : ""}</td><td className="px-4 py-3 text-right"><form action={action}><input type="hidden" name="coupon_id" value={coupon.id} /><input type="hidden" name="is_active" value={String(coupon.isActive)} /><button type="submit" disabled={!canManage || !schemaAvailable || pending} className="rounded-full bg-raised px-3 py-1.5 text-[10px] font-extrabold text-primary disabled:opacity-50">{pending ? "Saving…" : coupon.isActive ? "Pause" : "Resume"}</button></form></td></tr>;
}
