"use client";

import { useActionState, useState } from "react";
import { AdminIcon } from "@/components/admin/AdminIcon";
import {
  platformAnnouncementAudienceLabel,
  platformAnnouncementSeverityLabel,
  platformAnnouncementStatusLabel,
  PLATFORM_ANNOUNCEMENT_AUDIENCES,
  PLATFORM_ANNOUNCEMENT_SEVERITIES,
  type PlatformAnnouncement,
  type PlatformAnnouncementAudience,
  type PlatformAnnouncementSeverity,
} from "@/lib/platform-announcements";
import { savePlatformAnnouncement, setPlatformAnnouncementStatus, type AnnouncementActionState } from "./announcement-actions";

const INITIAL_STATE: AnnouncementActionState = { ok: false, message: "" };
const CONTROL_CLASS = "mt-1 w-full rounded-xl border border-line-strong bg-raised px-3 py-2.5 text-sm font-semibold text-ink outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10";

export function PlatformAnnouncementEditor({ announcements, schemaAvailable, canManage, editing = null }: { announcements: PlatformAnnouncement[]; schemaAvailable: boolean; canManage: boolean; editing?: PlatformAnnouncement | null }) {
  const [state, formAction, pending] = useActionState(savePlatformAnnouncement, INITIAL_STATE);
  const [audience, setAudience] = useState<PlatformAnnouncementAudience>(editing?.audience ?? "all");
  const [title, setTitle] = useState(editing?.title ?? "");
  const [body, setBody] = useState(editing?.body ?? "");
  const [severity, setSeverity] = useState<PlatformAnnouncementSeverity>(editing?.severity ?? "info");
  const [actionLabel, setActionLabel] = useState(editing?.actionLabel ?? "");
  return <>
    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.08fr)_minmax(300px,0.92fr)]">
      <form key={editing?.id ?? "new"} action={formAction} className="rounded-[20px] border border-line bg-surface p-5 shadow-[var(--shadow-card)] sm:p-6" aria-labelledby="create-announcement-heading">
        <div className="flex items-start justify-between gap-4 border-b border-line pb-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-accent">Publish an update</p><h2 id="create-announcement-heading" className="mt-1 text-xl font-extrabold tracking-[-0.025em]">{editing ? "Edit announcement" : "Create announcement"}</h2><p className="mt-1 max-w-xl text-sm leading-5 text-ink-muted">Draft a clear merchant-facing message, schedule it when needed, and retire it when the window closes.</p></div><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary-soft text-primary"><AdminIcon name="bell" size={17} /></span></div>

        <input type="hidden" name="id" value={editing?.id ?? ""} readOnly />
        <div className="mt-5 grid gap-3 sm:grid-cols-[minmax(0,1fr)_160px]"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-title">Title<input id="announcement-title" name="title" type="text" required maxLength={140} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Scheduled maintenance" className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-severity">Severity<select id="announcement-severity" name="severity" value={severity} onChange={(event) => setSeverity(event.target.value as PlatformAnnouncementSeverity)} className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending}>{PLATFORM_ANNOUNCEMENT_SEVERITIES.map((option) => <option key={option} value={option}>{platformAnnouncementSeverityLabel(option)}</option>)}</select></label></div>
        <label className="mt-3 block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-body">Message<textarea id="announcement-body" name="body" rows={5} required maxLength={5000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Tell merchants what is changing, when it starts, and what they should do." className={`${CONTROL_CLASS} resize-y`} disabled={!canManage || !schemaAvailable || pending} /></label>
        <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-audience">Audience<select id="announcement-audience" name="audience" value={audience} onChange={(event) => setAudience(event.target.value as PlatformAnnouncementAudience)} className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending}>{PLATFORM_ANNOUNCEMENT_AUDIENCES.map((option) => <option key={option} value={option}>{platformAnnouncementAudienceLabel(option, null)}</option>)}</select></label>{audience === "all" ? <div className="rounded-xl border border-line bg-raised px-3 py-3 text-xs font-semibold leading-5 text-ink-muted">All active merchant workspaces will see this announcement when it is published.</div> : <label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-audience-value">Audience value<input id="announcement-audience-value" name="audience_value" type="text" required maxLength={80} defaultValue={editing?.audienceValue ?? ""} placeholder={audience === "plan" ? "premium" : "suspended"} className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} />{audience === "account_status" && <span className="mt-1 block text-[10px] font-semibold text-ink-muted">Use active or suspended.</span>}</label>}</div>
        <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-starts">Starts (Singapore time, optional)<input id="announcement-starts" name="starts_at" type="datetime-local" defaultValue={dateTimeLocalValue(editing?.startsAt)} className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-expires">Expires (optional)<input id="announcement-expires" name="expires_at" type="datetime-local" defaultValue={dateTimeLocalValue(editing?.expiresAt)} className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label></div>
        <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-action-label">Action label (optional)<input id="announcement-action-label" name="action_label" type="text" maxLength={60} value={actionLabel} onChange={(event) => setActionLabel(event.target.value)} placeholder="Read the update" className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label><label className="block text-[10px] font-extrabold uppercase tracking-wide text-ink-muted" htmlFor="announcement-action-url">Action URL (optional)<input id="announcement-action-url" name="action_url" type="text" maxLength={500} defaultValue={editing?.actionUrl ?? ""} placeholder="/help/updates" className={CONTROL_CLASS} disabled={!canManage || !schemaAvailable || pending} /></label></div>

        {state.message && <p role={state.ok ? "status" : "alert"} className={`mt-4 rounded-xl border px-3 py-2.5 text-sm font-semibold ${state.ok ? "border-success/25 bg-success/10 text-success" : "border-danger/25 bg-danger-soft text-danger"}`}>{state.message}</p>}
        {!schemaAvailable && <p role="status" className="mt-4 rounded-xl border border-warning/35 bg-warning/10 px-3 py-2.5 text-xs font-semibold leading-5 text-ink">Announcement storage is not active yet. Apply <code className="font-extrabold">0085_platform_announcements.sql</code> before creating or publishing updates.</p>}
        {!canManage && <p role="status" className="mt-4 rounded-xl border border-line bg-raised px-3 py-2.5 text-xs font-semibold leading-5 text-ink-muted">Announcement publishing is reserved for Owner operators. Your role can still review the history below.</p>}
        <div className="mt-5 flex flex-col gap-2 border-t border-line pt-4 sm:flex-row"><button type="submit" name="intent" value="draft" disabled={!canManage || !schemaAvailable || pending} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-secondary px-4 py-3 text-xs font-extrabold uppercase tracking-wide text-primary transition hover:bg-secondary-hover disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving…" : "Save draft"}</button><button type="submit" name="intent" value="publish" disabled={!canManage || !schemaAvailable || pending} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-extrabold uppercase tracking-wide text-primary-fg transition hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving…" : editing ? "Save & publish" : "Publish announcement"}<AdminIcon name="arrow" size={14} /></button>{editing && <a href="/platform/announcements" className="inline-flex min-h-11 items-center justify-center rounded-xl border border-line-strong px-4 py-3 text-xs font-extrabold text-primary">Cancel</a>}</div>
      </form>

      <aside className="rounded-[20px] border border-line bg-primary p-5 text-primary-fg shadow-[var(--shadow-pop)] sm:p-6" aria-labelledby="announcement-rules-heading"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-primary-fg/65">Publishing rules</p><h2 id="announcement-rules-heading" className="mt-1 text-xl font-extrabold">Keep merchant updates calm and useful.</h2><p className="mt-2 text-sm leading-5 text-primary-fg/72">Use severity for urgency, schedule maintenance ahead of time, and include one clear action when a merchant needs to do something.</p><div className="mt-5 space-y-2.5"><RuleRow label="Draft" detail="Only platform operators can see it." /><RuleRow label="Scheduled" detail="Starts automatically at the selected time." /><RuleRow label="Published" detail="Available to the targeted audience until expiry." /><RuleRow label="Archived" detail="Removed from active delivery while history stays intact." /></div><div className="mt-5 rounded-[18px] bg-surface p-4 text-ink" aria-live="polite"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.13em] text-ink-muted">Merchant preview</p><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold ${severity === "critical" ? "bg-danger-soft text-danger" : severity === "warning" ? "bg-warning/15 text-ink" : severity === "success" ? "bg-success/10 text-success" : "bg-primary-soft text-primary"}`}>{platformAnnouncementSeverityLabel(severity)}</span></div><h3 className="mt-3 text-sm font-extrabold">{title.trim() || "Announcement title"}</h3><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-ink-muted">{body.trim() || "Your announcement message will appear here."}</p>{actionLabel.trim() && <span className="mt-3 inline-flex rounded-lg bg-primary px-3 py-2 text-[10px] font-extrabold text-primary-fg">{actionLabel.trim()}</span>}</div></aside>
    </section>

    <section className="mt-5 overflow-hidden rounded-[20px] border border-line bg-surface shadow-[var(--shadow-card)]" aria-labelledby="announcement-history-heading"><div className="flex flex-col gap-3 border-b border-line px-5 py-5 sm:flex-row sm:items-end sm:justify-between sm:px-6"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-accent">Announcement history</p><h2 id="announcement-history-heading" className="mt-1 text-xl font-extrabold tracking-[-0.025em]">Messages and lifecycle</h2><p className="mt-1 text-sm leading-5 text-ink-muted">Review what has been drafted, scheduled, published, or retired across the platform.</p></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-primary-soft px-3 py-1.5 text-xs font-extrabold text-primary"><AdminIcon name="bell" size={13} /> {announcements.length} message{announcements.length === 1 ? "" : "s"}</span></div>{announcements.length === 0 ? <div className="px-6 py-14 text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-primary-soft text-primary"><AdminIcon name="bell" size={19} /></span><p className="mt-3 text-sm font-extrabold text-ink">No announcements yet</p><p className="mt-1 text-xs leading-5 text-ink-muted">Create a draft above to start the platform communication history.</p></div> : <div className="divide-y divide-line">{announcements.map((announcement) => <AnnouncementRow key={announcement.id} announcement={announcement} schemaAvailable={schemaAvailable} canManage={canManage} />)}</div>}</section>
  </>;
}

function AnnouncementRow({ announcement, schemaAvailable, canManage }: { announcement: PlatformAnnouncement; schemaAvailable: boolean; canManage: boolean }) {
  return <article className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-start sm:justify-between sm:px-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold ${announcement.severity === "critical" ? "bg-danger-soft text-danger" : announcement.severity === "warning" ? "bg-warning/15 text-ink" : announcement.severity === "success" ? "bg-success/10 text-success" : "bg-primary-soft text-primary"}`}>{platformAnnouncementSeverityLabel(announcement.severity)}</span><span className="rounded-full bg-raised px-2.5 py-1 text-[10px] font-extrabold text-ink-muted">{platformAnnouncementStatusLabel(announcement.status)}</span><span className="text-[10px] font-semibold text-ink-muted">{platformAnnouncementAudienceLabel(announcement.audience, announcement.audienceValue)}</span></div><h3 className="mt-2 text-sm font-extrabold">{announcement.title}</h3><p className="mt-1 max-w-3xl whitespace-pre-wrap text-sm leading-5 text-ink-muted">{announcement.body}</p><p className="mt-2 text-[10px] font-semibold text-ink-muted">{dateLabel(announcement.startsAt, "Starts")} · {dateLabel(announcement.expiresAt, "Expires")}</p></div><div className="flex shrink-0 items-start gap-2"><a href={`/platform/announcements?edit=${encodeURIComponent(announcement.id)}`} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-line-strong bg-raised px-3 py-2 text-[10px] font-extrabold uppercase tracking-wide text-primary transition hover:border-primary hover:bg-primary-soft">Edit</a><AnnouncementStatusButton announcement={announcement} schemaAvailable={schemaAvailable} canManage={canManage} /></div></article>;
}

function AnnouncementStatusButton({ announcement, schemaAvailable, canManage }: { announcement: PlatformAnnouncement; schemaAvailable: boolean; canManage: boolean }) {
  const [state, formAction, pending] = useActionState(setPlatformAnnouncementStatus, INITIAL_STATE);
  const nextStatus = announcement.status === "published" ? "archived" : "published";
  const actionLabel = announcement.status === "archived" ? "Republish" : announcement.status === "published" ? "Archive" : "Publish";
  return <form action={formAction} className="flex shrink-0 flex-col items-end gap-1"><input type="hidden" name="id" value={announcement.id} readOnly /><input type="hidden" name="status" value={nextStatus} readOnly /><button type="submit" disabled={!canManage || !schemaAvailable || pending} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-line-strong bg-raised px-3 py-2 text-[10px] font-extrabold uppercase tracking-wide text-primary transition hover:border-primary hover:bg-primary-soft focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving…" : actionLabel}</button>{state.message && !state.ok && <span className="max-w-[170px] text-right text-[10px] font-semibold text-danger">{state.message}</span>}</form>;
}

function RuleRow({ label, detail }: { label: string; detail: string }) {
  return <div className="flex items-start gap-3 rounded-xl bg-primary-fg/10 px-3 py-2.5"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-accent text-accent-fg"><AdminIcon name="check" size={11} /></span><span><strong className="block text-xs font-extrabold">{label}</strong><span className="mt-0.5 block text-[11px] leading-4 text-primary-fg/65">{detail}</span></span></div>;
}

function dateLabel(value: string | null, label: string) {
  if (!value) return `${label} now`;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return `${label} unknown`;
  return `${label} ${new Intl.DateTimeFormat("en-PH", { month: "short", day: "numeric", year: "numeric", timeZone: "Asia/Singapore" }).format(date)}`;
}

function dateTimeLocalValue(value: string | null | undefined) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23", timeZone: "Asia/Singapore" }).formatToParts(date);
  const values = new Map(parts.map((part) => [part.type, part.value]));
  return `${values.get("year")}-${values.get("month")}-${values.get("day")}T${values.get("hour")}:${values.get("minute")}`;
}
